# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ignore duplicates or commands prepended with space
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=4000
HISTFILESIZE=4000

export LANG=en_GB.UTF-8
export LC_MESSAGES="C"
[[ $TERM == xterm ]] && export TERM=xterm-256color

# update LINES and COLUMNS after each command.
shopt -s checkwinsize

# Add color
alias less='less -R'
alias grep='grep --color=auto'
[[ `uname` == 'Darwin' ]] && alias ls='ls -G' || alias ls='ls --color=auto'

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

alias ls='ls --ignore=NTUSER.DAT* --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cls='tput reset'

alias bi='bundle ins'
alias be='bundle exec'
alias gfz="git st | sed 's/...//' | fzf"

# Clone or update a git repo
gup () {
  repo=$1; shift
  author=$1; shift
  dest=$1; shift

  if [[ $author = '--private' ]]; then
    host=$PRIVATE_GIT
  elif [[ ! $author ]]; then
    host=$PUBLIC_GIT
  else
    host=https://github.com/$author
  fi

  if [[ $dest = '' ]]; then
    dest=$repo
  fi

  if [ -d $dest ]; then
    echo updating $repo
    cd $dest
    git pull -q
    cd - > /dev/null
  else
    echo cloning $repo
    git clone -q $options $host/$repo $dest
  fi
}

export -f gup

if [ -d /usr/local/share/chruby ]; then
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
  chruby 2.4.1
fi

export FZF_DEFAULT_COMMAND='ag -g ""'
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

source ~/bashrc/prompt

if [ -f "/etc/arch-release" ]; then
  source ~/bashrc/archlinux/aliases
  source ~/bashrc/archlinux/functions
elif [ -d "/mnt/c" ]; then
  source ~/bashrc/wsl/startup
fi
