runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
Helptags
syntax enable
colorscheme hybrid
let g:molokai_original=0
filetype plugin indent on
highlight NonText ctermfg=0
highlight SignColumn ctermbg=8

set expandtab
set ignorecase
set incsearch
set noswapfile
set number
set shiftwidth=2
set smartcase
set tabstop=2
set tags=./tags
set wildignore+=*/.git/*,*/tmp/*,*/coverage/*,*/log/*,*/app/assets/fonts/*,*/app/assets/images/*,*/db/migrate/*,*/node_modules/*,*/bin/*

map <C-b> :NERDTreeToggle<CR>

map  <Esc>[; <C-Semicolon>
map! <Esc>[; <C-Semicolon>

nmap <C-n> :cn<CR>
nmap <C-m> :cp<CR>
nmap <Leader>n :setlocal number!<CR>
nmap <Leader>o :set paste!<CR>

noremap ; l
noremap l gk
noremap k gj
noremap j h
noremap h ;
noremap <C-j> <C-w>h
noremap <C-k> <C-w>j
noremap <C-l> <C-w>k
noremap <C-Semicolon> <C-w>l


" vim-rspec mappings
nnoremap <Leader>t :call RunCurrentSpecFile()<CR>
nnoremap <Leader>s :call RunNearestSpec()<CR>
nnoremap <Leader>l :call RunLastSpec()<CR>

" only highlight current line while in insert mode
augroup CursorLine
  au!
  au InsertEnter * setlocal cursorline
  au InsertLeave * setlocal nocursorline
augroup END

" remove trailing spaces
" remove extra lines at end of file
" insert single empty newline at end
function TrimTrailingSpacesAndNewLines()
  let cursor_pos = getpos('.')
  :silent! %s/\s\+$//e
  :silent! %s/\($\n\s*\)\+\%$/
  :silent! %s/\%$/\r
  call setpos('.', cursor_pos)
endfunction

autocmd BufWritePre * call TrimTrailingSpacesAndNewLines()

" quit vim if NERDTree is last window
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

"close NERDTree after opening file
let NERDTreeQuitOnOpen=1

let g:syntastic_javascript_checkers = ['eslint']

